apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: test-cluster-namespace

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
      - name: redis-container
        image: redis:alpine
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 6379