
name: result-app-ci

on:
    push:
        branches:
            - main
            - master

# This is going to prevent multiple workflow runs for the same branch. Same file will not be updated by multiple workflow runs at the same time. This is important because we are updating the deployment file in this workflow and if multiple workflow runs are trying to update the same file at the same time, it will create a conflict and the workflow will fail. So we are using concurrency to prevent that.

concurrency:
  group: deployment-manifest-update
  cancel-in-progress: false

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Install Dependencies
              working-directory: result
              run: |
                  npm ci

            - name: Run lint
              working-directory: result
              run: |
                  npm run lint --if-present

            #- name: Run Tests
            #  working-directory: result
            #  run: |
            #      npm run test

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./result
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/voting-application:resultapp-${{ github.run_id }}

            - name: update deployment file
              run: |
                  sed -i '/name: results-container/{n;s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/voting-application:resultapp-${{ github.run_id }}|;}' deployment.yml

            - name: commit changes
              run: |
                  git config user.name "${{ secrets.GIT_USERNAME }}"
                  git config user.email "${{ secrets.GIT_EMAIL }}"
                  git add deployment.yml
                  git commit -m "Update image tag [skip ci]" || exit 0

                  # This will prevent an error of modifying same deployment file. GitHub rejects it because the remote branch now contains a newer commit.

                  git pull --rebase origin master
                  git push origin master
